package com.primesprint.model.enums;

public enum ActionType {
    USER_CREATED,USER_UPDATED,USER_DEACTIVATED,REGISTER,USER_PROFILE_VIEWED,AI_REQUEST,ROLE_CHANGED,LOGIN,TEMPLATE_UPDATED,TEST_ACTION,PII_DETECTED, MASK_APPLIED, REHYDRATE_REQUESTED,DOCUMENT_UPLOADED;
}
